// migrations/add_shared_annotations.js — shared PDF markings (iPad app "Shared" layer).
// One row per stroke, attached to a SONG FILE (shows wherever that file is used). Strokes are drawn by admins and
// members with memberships.can_annotate_plans; every church member can read them.
//
// Follows the interim migration protocol (claude/running-backend-scripts.md): one transaction, idempotent,
// fails loud without DATABASE_URL, and verifies its own end state.
//
// Run:  cd ~/church-music/backend && DATABASE_URL='postgresql://…' node migrations/add_shared_annotations.js
const { Pool } = require('pg');

if (!process.env.DATABASE_URL) {
  console.error('DATABASE_URL is not set — refusing to run (would fall back to localhost).');
  process.exit(1);
}
const isLocal = /localhost|127\.0\.0\.1/.test(process.env.DATABASE_URL);
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: isLocal ? false : { rejectUnauthorized: false } });

async function run() {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    await client.query(`
      CREATE TABLE IF NOT EXISTS shared_annotations (
        id            UUID PRIMARY KEY,                 -- generated by the app (offline-safe, idempotent re-sends)
        church_id     UUID NOT NULL REFERENCES churches(id) ON DELETE CASCADE,
        song_file_id  UUID NOT NULL REFERENCES song_files(id) ON DELETE CASCADE,
        page          INTEGER NOT NULL CHECK (page >= 0),
        stroke        JSONB NOT NULL,                   -- { color, width, cap, join, pts: [[x,y],…] } normalised 0–1
        created_by    UUID REFERENCES users(id) ON DELETE SET NULL,
        created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `);
    await client.query('CREATE INDEX IF NOT EXISTS idx_shared_annotations_file ON shared_annotations (song_file_id)');
    await client.query('CREATE INDEX IF NOT EXISTS idx_shared_annotations_church ON shared_annotations (church_id)');
    await client.query('COMMIT');
  } catch (err) {
    await client.query('ROLLBACK');
    throw err;
  } finally {
    client.release();
  }

  // ---- Verify the END STATE (not just "no error") ----
  const cols = await pool.query(
    `SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'shared_annotations' ORDER BY ordinal_position`
  );
  const want = { id: 'uuid', church_id: 'uuid', song_file_id: 'uuid', page: 'integer', stroke: 'jsonb', created_by: 'uuid', created_at: 'timestamp with time zone' };
  const got = Object.fromEntries(cols.rows.map((r) => [r.column_name, r.data_type]));
  const missing = Object.entries(want).filter(([c, t]) => got[c] !== t);
  const idx = await pool.query(`SELECT indexname FROM pg_indexes WHERE tablename = 'shared_annotations'`);
  const idxNames = idx.rows.map((r) => r.indexname);
  const idxMissing = ['idx_shared_annotations_file', 'idx_shared_annotations_church'].filter((n) => !idxNames.includes(n));

  // Fire-test: insert + delete one row inside a transaction that always rolls back (proves FKs/constraints work).
  let fire = 'skipped (no song_files rows)';
  const f = await pool.query(`SELECT sf.id AS file_id, s.church_id FROM song_files sf JOIN songs s ON s.id = sf.song_id LIMIT 1`);
  if (f.rows.length) {
    const c = await pool.connect();
    try {
      await c.query('BEGIN');
      await c.query(
        `INSERT INTO shared_annotations (id, church_id, song_file_id, page, stroke) VALUES (uuid_generate_v4(), $1, $2, 0, $3)`,
        [f.rows[0].church_id, f.rows[0].file_id, JSON.stringify({ color: '#e23b3b', width: 3, cap: 'round', join: 'round', pts: [[0.1, 0.1]] })]
      );
      fire = 'PASS';
    } catch (e) {
      fire = 'FAIL: ' + e.message;
    } finally {
      await c.query('ROLLBACK');
      c.release();
    }
  }

  console.log('shared_annotations columns:', missing.length ? `MISSING/WRONG ${JSON.stringify(missing)}` : 'OK');
  console.log('indexes:', idxMissing.length ? `MISSING ${idxMissing.join(', ')}` : 'OK');
  console.log('fire-test (rolled back):', fire);
  const ok = !missing.length && !idxMissing.length && !fire.startsWith('FAIL');
  console.log(ok ? '✓ shared_annotations ready' : '✗ verification FAILED');
  await pool.end();
  process.exit(ok ? 0 : 1);
}

run().catch(async (err) => { console.error(err); await pool.end().catch(() => {}); process.exit(1); });
